--INSERT INTO prizes (name, rarity, five_star_type, description) VALUES
--('30-50CNY充入加密货币', 3, NULL, '三星奖品示例'),
--('200 CNY充入加密货币', 4, NULL, '四星奖品示例'),
--('普通五星奖品示例', 5, 'normal', '普通五星奖品描述'),
--('限定五星奖品示例', 5, 'limited', '限定五星奖品描述');
