name: Backend CI Workflow

on:
  push:
    branches:
      - main # 针对 main 分支
  pull_request:
    branches:
      - main # 针对 PR 请求

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 JDK 21 环境
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 选择 OpenJDK 的 temurin 版本
          java-version: '21' # 确保使用 JDK 21

      # 3. 缓存 Maven 依赖
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. 安装 Maven 依赖
      - name: Install Dependencies
        working-directory: ./lottery
        run: mvn install -DskipTests

      # 5. 运行测试
      - name: Run Tests
        working-directory: ./lottery
        run: mvn test

      # 6. 打包项目（可选）
      - name: Package project
        working-directory: ./lottery
        run: mvn package
