name: Backend CI Workflow

on:
  push:
    branches:
      - main # 针对 main 分支
  pull_request:
    branches:
      - main # 针对 PR 请求

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 选择 OpenJDK 的 temurin 版本
          java-version: '17' # 根据你的项目设置 Java 版本

      # 3. 安装 Maven 依赖
      - name: Install Dependencies
        working-directory: ./lottery
        run: mvn install -DskipTests

      # 4. 运行测试
      - name: Run Tests
        working-directory: ./lottery
        run: mvn test
